### ISSUE TITLE
Does not run on macOS 11

### ISSUE THREAD

**Issue by mnrkbys** [jamf/aftermath#41]
Hi, thanks for releasing aftermath.
I'm trying the features, but aftermath can not run on macOS 11.

```
% sw_vers 
ProductName:	macOS
ProductVersion:	11.7
BuildVersion:	20G817
% ./aftermath -h
dyld: Symbol not found: _$s10Foundation4DateV18ISO8601FormatStyleV0B13TimeSeparatorO8standardyA2GmFWC
  Referenced from: /Users/macforensics/Downloads/./aftermath (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/swift/libswiftFoundation.dylib
 in /Users/macforensics/Downloads/./aftermath
zsh: abort      ./aftermath -h
```
Doesn't Aftermath support macOS 11 and earlier?

**Comment by ofir13299** [comment]
I am joining @mnrkbys, not working on 11.3.1 as well.
Same error code.
![image](https://user-images.githubusercontent.com/49280838/196944232-87be8436-0b18-4d05-807b-a4c18144b404.png)
Is there any workaround for that?

**Comment by ofir13299** [comment]
Hi and thank you for this wonderful tool!
It works great on macOS Monterey.
Joining @mnrkbys, I'm facing the same issue on macOS 11.3.1.
Same error:
![image](https://user-images.githubusercontent.com/49280838/196945228-33bc30a6-f2bc-427a-8393-7a58e579096f.png)

Is there any workaround to make this tool support older versions of macOS? or a compatibility fix will take place, that will be great.

**Comment by mattbenyo** [comment]
updated in v1.2.0
