### ISSUE TITLE
fresh git clone and xcodebuild with errors

### ISSUE THREAD

**Issue by paulgagliardi** [jamf/aftermath#48]
I get a `aftermath/aftermath/CaseFiles.swift:9:8: error: no such module 'ZIPFoundation' import ZipFoundation` error after git clone and xcodebuild on Ventura 13.2

It does seem to resolve the dependency and build fine in full xcode but wondering what I'm doing wrong in the normal CLI here. It's always the damn dependency management and swift dep management is not something quick googling was able to help with here.

**Comment by paulgagliardi** [comment]
yes - exactly. just following the directions on the `build` part of the readme.md

**Comment by stuartjash** [comment]
if you run `xcodebuild -scheme "aftermath"` does that resolve it?

**Comment by paulgagliardi** [comment]
it sure does! thank you

**Comment by stuartjash** [comment]
Thanks for bringing this to my attention. I’ll get the README updated. 🙏On Feb 13, 2023, at 5:39 PM, Paul Gagliardi ***@***.***> wrote:﻿
it sure does! thank you
